replicaCount: 1

image:
  repository: docker.io/library/mongo
  tag: "6.0"

persistence:
  size: 5Gi
  storageClassName: ""

mongo:
  username: "adminuser"
  password: "mi_password"  # ⚠️ Será reemplazado por GitHub Actions
  database: "commentsdb"
