apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret   # ⚠️ Cambiado de mongo-secret a mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  username: {{ .Values.mongo.username | quote }}
  password: {{ .Values.mongo.password | quote }}
